---
 - hosts: Pc-admin
   become: yes
   tasks:
      - name: Copying doc 
        copy:
          src: ../data/pcc_admin
          dest: /home/etudiant/Documents
          owner: etudiant
          group: etudiant
          mode: 0755
      - name: Install boxes Gitea, Zabbix, Netbox on the admin computer
        command: "cd /home/etudiant/Documents/pcc_admin"
        command: "vagrant up"

 - hosts: Pc-web
   become: yes
   tasks:
      - name: Copying doc 
        copy:
          src: ../data/pcc_web
          dest: /home/etudiant/Documents
          owner: etudiant
          group: etudiant
          mode: 0755
      - name: Install boxes Gitea, Zabbix, Netbox on the admin computer
        command: "cd /home/etudiant/Documents/pcc_web"
        command: "vagrant up"


 - hosts: Pc_database
   become: yes
   tasks:
      - name: Copying doc 
        copy:
          src: ../data/pcc_bdd
          dest: /home/etudiant/Documents
          owner: etudiant
          group: etudiant
          mode: 0755
      - name: Install boxes Gitea, Zabbix, Netbox on the admin computer
        command: "cd /home/etudiant/Documents/pcc_database"
        command: "vagrant up"


 - hosts: Pc_secu
   become: yes
   tasks:
      - name: Copying doc 
        copy:
          src: ../data/pcc_securite
          dest: /home/etudiant/Documents
          owner: etudiant
          group: etudiant
          mode: 0755
      - name: Install boxes Gitea, Zabbix, Netbox on the admin computer
        command: "cd /home/etudiant/Documents/pcc_securite"
        command: "vagrant up"


 - hosts: Pc_sauvegarde
   become: yes
   tasks:
      - name: Copying doc 
        copy:
          src: ../data/pcc_sauvegarde
          dest: /home/etudiant/Documents
          owner: etudiant
          group: etudiant
          mode: 0755
      - name: Install boxes Gitea, Zabbix, Netbox on the admin computer
        command: "cd /home/etudiant/Documents/pcc_sauvegarde"
        command: "vagrant up"

